version: '2'
services:
  bot:
    image: python:3.7
    container_name: 'zolobot'
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      WOLFRAM_ALPHA_APP_ID: ${WOLFRAM_ALPHA_APP_ID}
    restart: always
    volumes:
      - ./bot:/bot
    working_dir: /bot
    command: bash -c "pip install -r requirements.txt && python -u core.py"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - db-data:/data/db
volumes:
  db-data:
    driver: local
