name: Build and push image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/cybermouflons/ovisbot:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Write Secret to .env File
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > .env
          echo ".env file created with the contents of ENV_FILE secret"

      - name: Set up SSH for Deployment
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: >
          apt-get update && apt-get install -y sshpass
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "mkdir -p ~/ovisbot"

      - name: Upload Code to Server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: >
          sshpass -p "$SSH_PASSWORD" rsync -avz --exclude '.git' ./
          "$SSH_USER@$SSH_HOST:~/ovisbot"

      - name: Deploy Application
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: >
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no
          "$SSH_USER@$SSH_HOST" << 'EOF'
            cd ~/ovisbot
            if [ -f docker-compose.yml ]; then
              docker compose -f docker-compose.yml -f docker-compose.prod.yml down || true
              docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
              docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
            else
              echo "docker-compose.yml not found in the repository!"
              exit 1
            fi
          EOF
